### ISSUE TITLE
Error in console, translatetochinese node is red in comfyui

### ISSUE THREAD

**Issue by Serge108** [BetaDoggo/ComfyUI-Kolors-Translator#1]
```
## Execute install/(de)activation script for 'G:\_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-Translator'
 Collecting llama-cpp-python
   Using cached llama_cpp_python-0.2.82.tar.gz (50.7 MB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'done'
[!] ERROR: Exception:
[!] Traceback (most recent call last):
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
[!]     status = run_func(*args)
[!]              ^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
[!]     return func(self, options, args)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
[!]     requirement_set = resolver.resolve(
[!]                       ^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
[!]     result = self._result = resolver.resolve(
[!]                             ^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
[!]     state = resolution.resolve(requirements, max_rounds=max_rounds)
[!]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
[!]     self._add_to_criteria(self.state.criteria, r, parent=None)
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
[!]     if not criterion.candidates:
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
[!]     return bool(self._sequence)
[!]            ^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
[!]     return any(self)
[!]            ^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
[!]     return (c for c in iterator if id(c) not in self._incompatible_ids)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
[!]     candidate = func()
[!]                 ^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 185, in _make_candidate_from_link
[!]     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
[!]                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 231, in _make_base_candidate_from_link
[!]     self._link_candidate_cache[link] = LinkCandidate(
[!]                                        ^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__
[!]     super().__init__(
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__
[!]     self.dist = self._prepare()
[!]                 ^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
[!]     dist = self._prepare_distribution()
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
[!]     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
[!]     return self._prepare_linked_requirement(req, parallel_builds)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
[!]     dist = _get_prepared_distribution(
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
[!]     abstract_dist.prepare_distribution_metadata(
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
[!]     self._install_build_reqs(finder)
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
[!]     build_reqs = self._get_build_requires_wheel()
[!]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
[!]     return backend.get_requires_for_build_wheel()
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 709, in get_requires_for_build_wheel
[!]     return super().get_requires_for_build_wheel(config_settings=cs)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
[!]     return self._call_hook('get_requires_for_build_wheel', {
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
[!]     raise BackendUnavailable(data.get('traceback', ''))
[!] pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[!]   File "G:\_ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
[!]     obj = import_module(mod_path)
[!]           ^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "importlib\__init__.py", line 126, in import_module
[!]   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
[!]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[!]   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
[!] ModuleNotFoundError: No module named 'scikit_build_core'
[!]
[!]
[!] [notice] A new release of pip is available: 24.1.1 -> 24.1.2
[!] [notice] To update, run: G:\_ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
install/(de)activation script failed: G:\_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-Translator
```

**Comment by BetaDoggo** [comment]
~~It's trying to compile llama-cpp-python instead of installing the compiled wheel that I specified in the requirements.txt. It's likely that I misunderstood how comfy manager gets dependencies.~~
~~To install the compiled version run this command from a powershell window in your _ComfyUI_windows_portable folder:~~

~~`.\python_embeded\python.exe -m pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu`~~

~~Let me know if that works or if you need more guidance. I'll look into why it isn't getting the correct version.~~

**Comment by BetaDoggo** [comment]
I believe I've fixed this now. Delete `ComfyUI-Kolors-Translator` from `custom_nodes` then do the "Install via git url" again.

**Comment by Serge108** [comment]
Hi, I deleted the old folder and reinstalled with manager using "Installing via Git URL" button.
The console output goes like this: 

Install: ['https://github.com/BetaDoggo/ComfyUI-Kolors-Translator.git']
Download: git clone 'https://github.com/BetaDoggo/ComfyUI-Kolors-Translator.git'
[!]
100%|██████████| 18.0/18.0 [00:00<00:00, 21.36it/s]
100%|██████████| 18.0/18.0 [00:00<00:00, 21.36it/s]
100%|██████████| 16.0/16.0 [00:00<00:00, 18.96it/s]
100%|██████████| 16.0/16.0 [00:00<00:00, 18.96it/s]
100%|██████████| 18.0/18.0 [00:01<00:00, 15.56it/s]
100%|██████████| 18.0/18.0 [00:01<00:00, 15.56it/s]
100%|██████████| 5.0/5.0 [00:01<00:00,  4.32it/s]
100%|██████████| 5.0/5.0 [00:01<00:00,  4.32it/s]
100%|██████████| 5.0/5.0 [00:01<00:00,  3.26it/s]
Install: pip packages
Installation was successful.
After restarting ComfyUI, please refresh the browser.


#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['G:\\_ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu']

## Execute install/(de)activation script for 'G:\_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-Translator'
[!] ERROR: Invalid requirement: 'llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu': Expected end or semicolon (after name and no valid version specifier)
[!]     llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
[!]                      ^
[!]
[!] [notice] A new release of pip is available: 24.1.1 -> 24.1.2
[!] [notice] To update, run: G:\_ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
install/(de)activation script failed: G:\_ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-Translator

**Comment by Serge108** [comment]
seems like that the problem is also that I do not have c++ tools, so I cant compile llama-cpp

**Comment by Serge108** [comment]
seems like that the problem is also that I do not have c++ tools, so I cant compile llama-cpp

**Comment by Serge108** [comment]
with help, I have downloaded a precompiled whl and installed it. The node lit green and the download of the model started after I had ran the workflow. I will track this thread from time to time for your reply, but specificaly for me the issue is somewhat solved

**Comment by BetaDoggo** [comment]
Good to hear you got it working. I ultimately ended up removing the automatic install instructions because I couldn't get ComfyManager to install the precompiled version properly.
